### ISSUE TITLE
Salt 2016.11 not included in stable version options?

### ISSUE THREAD

**Issue by moop-moop** [saltstack/salt-bootstrap#1020]
### Description of Issue/Question
Version 2016.11 is not included as a valid stable branch

### Setup
https://github.com/saltstack/salt-bootstrap/blob/stable/bootstrap-salt.sh#L527

### Steps to Reproduce Issue
install_salt.sh -P stable 2016.11
Unknown stable version: 2016.11 (valid: 1.6, 1.7, 2014.1, 2014.7, 2015.5, 2015.8, 2016.3, latest, $MAJOR.$MINOR.$PATCH)

### Versions and Systems
Stable bootstrap script 2017.01.10
seems to be included in the current development branch

**Comment by rallytime** [comment]
Hi @moop-moop - yeah that was an oversight on our part. This should be fixed in the `develop` branch now with PR #1017.

This fix will be available in the next release, but we usually only release every couple of months. You can grab the develop script [here](https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh) which has the change.
