### ISSUE TITLE
Doesn't ensure that python dev headers are installed.

### ISSUE THREAD

**Issue by melinath** [saltstack/salt-bootstrap#105]
Ran into an issue using bootstrapper - zmq couldn't build because python dev headers were missing. Specifically, got this error:

`buildutils/initlibzmq.c:10:20: fatal error: Python.h: No such file or directory`

**Comment by melinath** [comment]
I was using -P.

**Comment by s0undt3ch** [comment]
Could you show us the full output adding `-D` to the args?

**Comment by melinath** [comment]
Unfortunately, I wrote this ticket as I was installing the python dev headers. The install worked fine after that. Would it still be useful to have the output?

**Comment by s0undt3ch** [comment]
Well, since its no longer possible, what distro was this, it's version an which type of install; git, stable, etc....

That would already help out...

## 

Pedro Algarvio @ phone

----- Reply message -----
De: "Stephen Burrows" notifications@github.com
Para: "saltstack/salt-bootstrap" salt-bootstrap@noreply.github.com
Cc: "Pedro Algarvio" pedro@algarvio.me
Assunto: [salt-bootstrap] Doesn&apos;t ensure that python dev headers are installed. (#105)
Data: sáb, Abr 6, 2013 00:28
Unfortunately, I wrote this ticket as I was installing the python dev headers. The install worked fine after that. Would it still be useful to have the output? 

&mdash;

**Comment by melinath** [comment]
git develop, debian 7.

**Comment by s0undt3ch** [comment]
Were you using the `http://bootstrap.saltstack.org` one liner? This seems to be fixed in the current develop branch.

**Comment by melinath** [comment]
I was using that one liner, yes.

**Comment by akoumjian** [comment]
@s0undt3ch Is it fixed in bootstrap stable?

**Comment by s0undt3ch** [comment]
Not yet. It is in develop though.

**Comment by akoumjian** [comment]
@melinath : To clarify, @s0undt3ch is saying that there was a bug in bootstrap script stable. To test the bootstrap script in develop, which has supposedly fixed this issue, use the same one liner except replace the url with something like this:

https://raw.github.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh

It would be useful for us to know if this solved the problem.

**Comment by akoumjian** [comment]
...And literally as I posed this, @s0undt3ch updated stable branch. :-)

**Comment by s0undt3ch** [comment]
Yep! This is now fixed! And tested on 2 different Debian 7 (EC2 AMI's)

Attention: Only git based installations are available.
