### ISSUE TITLE
Cannot install standalone minion on kde neon

### ISSUE THREAD

**Issue by EHJ-52n** [saltstack/salt-bootstrap#1050]
# Description of Issue

## Setup
- *Script start:*
   ```
    *  INFO: Running version: 2017.01.10
    *  INFO: Executed by: sh
    *  INFO: Command line: './bootstrap_salt.sh '
   
    *  INFO: System Information:
    *  INFO:   CPU:          GenuineIntel
    *  INFO:   CPU Arch:     x86_64
    *  INFO:   OS Name:      Linux
    *  INFO:   OS Version:   4.8.0-46-generic
    *  INFO:   Distribution: Debian 16.04
   ```
- `lsb_release -a`:
   ```
   No LSB modules are available.
   Distributor ID: neon
   Description:    KDE neon User Edition 5.9
   Release:        16.04
   Codename:       xenial
   ```

## Steps to Reproduce Issue
1. Install latest kde neon
1. Open terminal
1. Execute the following two commands (Documentation: [Salt Masterless Quickstart](https://docs.saltstack.com/en/latest/topics/tutorials/quickstart.html#salt-masterless-quickstart)):
   ```
   $ curl -L https://bootstrap.saltstack.com -o bootstrap_salt.sh
   $ sudo sh bootstrap_salt.sh
   ```

## Versions and Systems
-  *Salt version*:
   ```
   $ salt --versions-report
   The program 'salt' is currently not installed. You can install it by typing:
   sudo apt install salt-master
   ```
- *Salt bootstrap*:
   ```
   $ sudo sh ./bootstrap_salt.sh -v
   ./bootstrap_salt.sh -- Version 2017.01.10
   ```
- *salt-call*:
   ```
   $ salt-call --version
   salt-call 2015.8.8 (Beryllium)
   ```

## Solution

```
--- bootstrap_salt.sh   2017-04-19 21:07:17.731136826 +0200
+++ bootstrap_salt_fixed.sh     2017-04-19 20:53:02.658094547 +0200
@@ -959,6 +959,8 @@
            DISTRO_NAME="Debian"
         elif [ "${DISTRO_NAME}" = "Cumulus Linux" ]; then
             DISTRO_NAME="Debian"
+        elif [ "${DISTRO_NAME}" = "neon" ]; then
+            DISTRO_NAME="Debian"
         fi
         rv=$(lsb_release -sr)
         [ "${rv}" != "" ] && DISTRO_VERSION=$(__parse_version_string "$rv")
```

**Comment by rallytime** [comment]
Hi @EHJ-52n - Would you be willing to submit a change for this? We'd gladly merge a fix for this issue if you're so inclined. Otherwise, we can grab this.

**Comment by vutny** [comment]
According to the official [FAQ](https://neon.kde.org/faq) and `lsb_release` output, it appears that KDE neon distro is based on latest Ubuntu LTS. So I think we should put the code for detecting this "derivative" to the appropriate section with other Ubuntu-based distros.

Also, I'm thinking about adding some more general checks to detect base distros, since hard-coding the names for every assembly on top of popular OS looks to me as not the best approach.

**Comment by EHJ-52n** [comment]
Hi @vutny,
I fully agree with you, that merging the ubuntu based distros or implementing a better "derivative" handling will be lasting longer. But I think, I will not be able to provide a solution for this.
The patch provided is a one-shot workaround for myself getting the stuff running. So, investing some more time for a better more generic solution, would be better.
But I am willing to test the solutions you provide.
Kind regards!

**Comment by vutny** [comment]
Yeah, my second statement was about future development approach in general, not a strict guidance :smile: 

Speaking about your quick fix, it definitely works, because the functions and packages for both Debian and Ubuntu don't differ that much. But anyhow, the code to detect `neon` "distro" should be placed to the `__ubuntu_derivatives_translation()` function: https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L1268
Seems like an easy doable.

@rallytime Just another note, the `$DISTRO_NAME` variable only used for debug output purposes and should not be redefined for any detected derivative. The `$DISTRO_NAME_L` does the real job, it should contain base distro name in lowercase. That part of code, posted by @EHJ-52n above, is unnecessary and may (actually does) confuse users and other contributors. It needs to be fixed.

**Comment by rallytime** [comment]
@vutny Yeah, you're right. Would you mind filing a new issue about that so we don't forget to clean it up?

**Comment by vutny** [comment]
Sure thing. I shall fill an issue or just fix it right away :smiley:

**Comment by EHJ-52n** [comment]
@vutny 
I fixed the `__ubuntu_derivatives_translation()` function as requested. Please see PR https://github.com/saltstack/salt-bootstrap/pull/1058 for more details.

**Comment by rallytime** [comment]
Thanks for submitting the fix for this @EHJ-52n! Since you're fix has now been merged, it this good to close?

**Comment by EHJ-52n** [comment]
@rallytime 
I think so, too.
