### ISSUE TITLE
powershell sat-minion on windows is breaking!

### ISSUE THREAD

**Issue by hemantaltair** [saltstack/salt-bootstrap#1394]
### Setup
(Please provide relevant configs (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
PS C:\Users\saltmaster> .\bootstrap-salt.ps1 -minion windows -master 10.4.2.4
The variable cannot be validated because the value Latest is not a valid value for the version variable.
At C:\Users\saltmaster\bootstrap-salt.ps1:234 char:18
+     $version = $($returnMatches[$returnMatches.Count -1]).Split(("n-" ...
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ValidationMetadataException
    + FullyQualifiedErrorId : ValidateSetFailure
 
Exception calling "Substring" with "2" argument(s): "Index and length must refer to a location within the string.
Parameter name: length"
At C:\Users\saltmaster\bootstrap-salt.ps1:239 char:1
+ $year = $version.Substring(0, 4)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException
 
Downloading Salt minion installer Salt-Minion--AMD64-Setup.exe
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At C:\Users\saltmaster\bootstrap-salt.ps1:257 char:1
+ $webclient.DownloadFile($url, $file)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
Installing Salt minion
Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
At C:\Users\saltmaster\bootstrap-salt.ps1:276 char:1
+ Start-Process C:\Windows\Temp\$saltExe -ArgumentList "/S $parameters" ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

### Versions and Systems
(`salt --versions-report`, `bootstrap-salt.sh -v`, system type and version,
cloud/VM provider as appropriate.)

**Comment by bobafouette** [comment]
Hello,

I ran into the exact same issue this morning. Every thing was fine yesterday.

I took a quick look into the bootstrap.ps1 script: 

At the very begining the of it `$version` param is declared and expected to [match](https://github.com/saltstack/salt-bootstrap/blob/stable/bootstrap-salt.ps1#L78-L81): `^201\d\.\d{1,2}\.\d{1,2}(\-\d{1})?|(rc\d)$`.

[Later on ](https://github.com/saltstack/salt-bootstrap/blob/stable/bootstrap-salt.ps1#L217-L235)if no param $version is provided the script tries to pull the latest version. The existing salt installer names for windows are listed and the version is extracted from the name of the last installer in the list. Which seems to currently be `Latest`. 
`Latest` do not match the $version's `ValidatePattern`. I thinks that's the issue here.

In the other hand all the `Latest` named installers have been released at least 10 days ago:

![image](https://user-images.githubusercontent.com/24678300/69638508-1e9e9880-105b-11ea-980b-10761f1cd670.png)

Therefore I do not understand why we are having this problem just today...

Edit: This might be in relation with #1392

**Comment by arizvisa** [comment]
Can some maintainer please to god look at this?

**Comment by s0undt3ch** [comment]
@twangboy could you take a look here when possible?
Thanks!

**Comment by arizvisa** [comment]
Also, if you guys plan to support Windows 7 as per the SaltStack-Supported-Operating-Systems matrix (http://get.saltstack.com/rs/304-PHQ-615/images/SaltStack-Supported-Operating-Systems.pdf), you'll need to sort out #1406 too as W7's bundled .NET Framework doesn't support those enumerations (but does support most of the constants themselves).

**Comment by bryceml** [comment]
Which versions of windows are you guys seeing this on, I see no issues on Windows 10 Pro release 1903.

**Comment by arizvisa** [comment]
@bryceml, W7. But the code that @loup-kreidl pointed out shows that "Latest" does not match the validation pattern of the version parameter so if it actually works on Windows 10, then the difference could be in powershell versions between all the platforms you guys claim to support.

**Comment by bryceml** [comment]
@hemantaltair can this be closed now?  did the change @twangboy make fix it for you?

**Comment by hemantaltair** [comment]
Yes thank you
