### ISSUE TITLE
[Feature Request] Add option to only configure repository

### ISSUE THREAD

**Issue by blarghmatey** [saltstack/salt-bootstrap#1497]
### Description of Issue/Question
It would be nice to be able to use the bootstrap script to set up the appropriate package repository for the given distribution without having to install the salt-minion or other packages. The use case here being that I would like to use the bootstrap script to populate the package repo using the `runcmd` stage of cloud-init and then use the `salt-minion` module subsequently to handle installing the minion package and populate the config and minion keys. When using the bootstrap script to install the minion it automatically generates keys which then fail to be accepted, vs the already accepted keys that I am passing to the salt-minion cloud-init module.

**Comment by dmurphy18** [comment]
@blarghmatey What you are wanting is available from the Install Instructions, https://docs.saltproject.io/salt/install-guide/en/latest/, take a look at https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/rhel.html#install-salt-on-redhat-rhel-9-x86-64 for example installing for RedHat 9, and how to setup repository information to allow you to access the Salt repositories.

Closing this feature request since a method is already available to achieve the same outcome.  Please reopen if there are additional details as to the Feature Request you are requesting.
