### ISSUE TITLE
Does this script work offline?

### ISSUE THREAD

**Issue by orientalperil** [saltstack/salt-bootstrap#15]
What's the recommended way using Salt to configure a machine that has no network access?

**Comment by akoumjian** [comment]
Well, I'm guessing you want to run a masterless minion. This means that your formulas are going to live directly on the minion. It also means you will issue commands to the minion on the machine directly using `salt-call --local [cmd]` instead of the usual targetting `salt '\*' [cmd]`. See http://docs.saltstack.org/en/latest/topics/tutorials/quickstart.html

As far as installing salt itself, it would probably be whatever method you use to install anything on the machine without network access. Probably scp over the correct package for your distro and install it that way.

I'm not sure how useful salt will be on a system without network access though. You're going to have to manually copy over any packages, files, and other things you want the system to have when it's done.

**Comment by orientalperil** [comment]
The goal is probably best achieved by exporting the virtual machine :).
