### ISSUE TITLE
Archlinux bootstrap fails

### ISSUE THREAD

**Issue by teburd** [saltstack/salt-bootstrap#163]
Bootstrapping archlinux with salt fails, the reason seems to be the boostrap script doesn't add a signing key for the package repo or disable package signing checking from the salt repo.

Either way would work, but signing and adding the signing key is probably the nicer way.

**Comment by s0undt3ch** [comment]
This issue has been fixed, though the problem still exists if you're bootstrapping on a system which had the salt repository added previously.
Was that not the reason?

**Comment by teburd** [comment]
It wasn't, I was using the salt vagrant plugin, like...

vagrant plugin install salt

**Comment by s0undt3ch** [comment]
And what was the version of the bootstrap script? Shows up on the bootstrapping logs

**Comment by teburd** [comment]
It was using 1.5.2, I told it to use a newer version so now it bootstraps but my config file is now moved.

Pacman will move files that exist and don't belong to a package to pacorig if a package your installing uses that file path.

salty vagrant, the boot strap, and a custom minion config for masterless operation seems to be problematic because of this atm.

**Comment by s0undt3ch** [comment]
The problem is that your pacman config already includes a salt entry, right? Remove it and run the bootstrap script again.

## 

Pedro Algarvio @ phone

----- Reply message -----
De: "Tom Burdick" notifications@github.com
Para: "saltstack/salt-bootstrap" salt-bootstrap@noreply.github.com
Cc: "Pedro Algarvio" pedro@algarvio.me
Assunto: [salt-bootstrap] Archlinux bootstrap fails (#163)
Data: ter, Jun 18, 2013 04:41
It was using 1.5.2, I told it to use a newer version so now it bootstraps but my config file is now moved. 

Pacman will move files that exist and don't belong to a package to pacorig if a package your installing uses that file path. 

salty vagrant, the boot strap, and a custom minion config for masterless operation seems to be problematic because of this atm. 

&mdash;

**Comment by teburd** [comment]
Its not a problem with the arch packaging or my pacman config, its a problem with the order in which things happen.

Docs about what happens in this case with archlinux package management, https://wiki.archlinux.org/index.php/Pacnew_and_Pacsave_Files#.pacorig

The order needs to be
- Install salt package
- Copy configs to proper location
- Start salt daemons

According to the salty-vagrant maintainer this is a bootstrap script issue as the config salty-vagrant gives to the vm is put in some tmp location not in /etc/salt?

In any case the order is wrong here somehow. The config file is copied first right now.

**Comment by s0undt3ch** [comment]
Yes, this issue belongs in the bootstrap script. I'll see what we can do.

**Comment by s0undt3ch** [comment]
This is not the proper fix. Sorry @bfrog. This is now handled in #168.

**Comment by s0undt3ch** [comment]
@bfrog could you please test the latest development branch?

For example:

```
curl -L https://raw.github.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh | \
    sudo sh -s -- git develop
```
