### ISSUE TITLE
Install script choose EPEL package instead of PyPi even when using the -P parameter

### ISSUE THREAD

**Issue by JeremieCharest** [saltstack/salt-bootstrap#177]
When using the following command on a CentOs 6.4, the installer prefer the Epel version which is not the latest and didn't use the pip artifact.

 wget -O - http://bootstrap.saltstack.org | sh -s -- -P
//INFO: Running install_centos_stable()

pip search salt
...
 INSTALLED: 0.15.3
 LATEST:    0.16.0

salt-call --version  # salt-call 0.15.3

How can we force to use latest version?

**Comment by s0undt3ch** [comment]
The pip flag does not force the pypi version to be installed. It allows the pip version to be installed if that's required by the install function.

And if you're after the bleeding edge, pass 'git develop' as arguments to the script. Note that you can also pass a git tag, for example v0.16.0
This will install from git as opposed to install using system packages.

Anyway, I'll look into it as soon as I get a chance.

## 

Pedro Algarvio @ phone

----- Reply message -----
De: "evilNullPointer" notifications@github.com
Para: "saltstack/salt-bootstrap" salt-bootstrap@noreply.github.com
Assunto: [salt-bootstrap] Install script choose EPEL package instead of PyPi even when using the -P parameter (#177)
Data: sex, Jul 5, 2013 14:07
When using the following command on a CentOs 6.4, the installer prefer the Epel version which is not the latest and didn't use the pip artifact. 

wget -O - http://bootstrap.saltstack.org | sh -s -- -P 
-  INFO: Running install_centos_stable() 

pip search salt

...

INSTALLED: 0.15.3

LATEST:    0.16.0 

salt-call --version  # salt-call 0.15.3 

How can we force to use latest version? 

&mdash;

**Comment by s0undt3ch** [comment]
Ok, so in order to answer your question and close this issue, to install the latest version, if that's not available from the packages repository, you can install using a git checkout. Current latest is `0.16.2` so:

```
wget -O - http://bootstrap.saltstack.org | sh -s -- -P git v0.16.2
```
