### ISSUE TITLE
salt-bootstraps fails to run install_ubuntu_stable_deps() because SALTSTACK-GPG-KEY.pub url is returning 404

### ISSUE THREAD

**Issue by ashaker-cig** [saltstack/salt-bootstrap#1811]
### Description of Issue/Question

salt-bootstraps fails to run install_ubuntu_stable_deps() because SALTSTACK-GPG-KEY.pub url is returning 404

 * ERROR: https://repo.saltstack.com/py3/ubuntu/20.04/amd64/archive/3004/SALTSTACK-GPG-KEY.pub failed to download to /tmp/salt-gpg-e6Zqi61M.pub
 * ERROR: Failed to run install_ubuntu_stable_deps()!!!

### Setup

 *  INFO: Running version: 2020.10.20
 *  INFO: Executed by: /bin/sh
 *  INFO: Command line: '/tmp/.saltcloud-b5408dde-28c2-4d67-82b0-23ee17e38721/deploy.sh -c /tmp/.saltcloud-b5408dde-28c2-4d67-82b0-23ee17e38721 stable 3004'

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   5.11.0-1027-aws
 *  INFO:   Distribution: Ubuntu 20.04

### Steps to Reproduce Issue
bootstrap-salt.sh stable 3004

**Comment by dmurphy18** [comment]
@ashaker-cig the URL https://repo.saltstack.com/py3/ubuntu/20.04/amd64/archive/3004/SALTSTACK-GPG-KEY.pub is no longer valid as Salt 3004 has been moved to archive.repo due to CVE.  See the announcement in many areas yesterday.

Salt 3004.1 is the latest valid version of Salt.

Please consider closing this issue, if the explanation is satisfactory

**Comment by ashaker-cig** [comment]
Thank you for your swift response!
