### ISSUE TITLE
How to install Saltstack on Rocky Linux 8 ARM architecture with python 3.6?

### ISSUE THREAD

**Issue by vanshikw** [saltstack/salt-bootstrap#1929]
Hi, There is a hard dependency on my side where I have to install Python 3.6 version only.
Please provide me with the working steps to install saltstack on my machine which has OS Rocky Linux 8 ARM having Python version 3.6

**Comment by dmurphy18** [comment]
@vanshikw There is no support for Python 3.6 with Salt, minimum version of Python support is 3.10, and only onedir (3006 and higher) versions of Salt are supported with current bootstrap.  Closing this as fixed in release of the bootstrap 2024-07-12, see https://github.com/saltstack/salt-bootstrap/actions/workflows/ci.yml.  Please feel free to reopen if other matters relevant to this issue come to light.

Note, that the onedir architecture has its own internal Python, and even Python 3.7 is EOL at this point, and 3.8 only getting security fixes, part of the reason for onedir, old OS's with EOL versions of Python.
