### ISSUE TITLE
Bootstrap no longer works for version 3005 in Amazon Linux 2

### ISSUE THREAD

**Issue by NickSchleicher** [saltstack/salt-bootstrap#2008]
### Description of Issue/Question
GPG retrieval failing for Amazon Linux 2 with Version 3005

### Setup
(Please provide relevant configs (Be sure to remove sensitive info).)
Execute bootstrap script from AL2 machine

### Steps to Reproduce Issue
curl -L https://bootstrap.saltstack.com -o install_salt.sh
sh install_salt.sh -A $SALT_MASTER -i $NODE_NAME stable 3005

### Versions and Systems
install_salt.sh -- Version 2024.07.12

Salt 3005 is still in Phase 3 support, but what version does salt-bootstrap support? I noticed that only >=3006 was tested for this build's CI

**Comment by dmurphy18** [comment]
@NickSchleicher The latest bootstrap script no longer supports BSD, Solaris, Python 2, and version of Salt which are EOL, The automated changelog generator over-wrote my change comments :( on that, sorry.
If you use 3005, or any of the above, then you need to use an earlier version of the bootstrap script, before changes in 2024.07 versions.
Currently updating the README, and I will be sure to add a piece stating that.
As per https://docs.saltproject.io/salt/install-guide/en/latest/topics/salt-version-support-lifecycle.html#older-version-support-lifecycle, Phase 3 support for 3005 ended on Feb 25, 2024, it is now July.

Closing this since Salt 3005 is EOL, but I will be sure to point this out in the README

**Comment by NickSchleicher** [comment]
Thanks @dmurphy18 I had misread that table and see that we're now in "extended life support"

**Comment by dmurphy18** [comment]
See https://github.com/saltstack/salt-bootstrap/pull/2009 for new README.rst

Should be near the top of the README about older versions.
