### ISSUE TITLE
https://docs.saltproject.io certificate is broken

### ISSUE THREAD

**Issue by neopointer** [saltstack/salt-bootstrap#2023]
The same goes to: https://bootstrap.saltproject.io

<img width="1006" alt="image" src="https://github.com/user-attachments/assets/24ee9a00-0eee-4ede-a513-e81f88a088e8">

**Comment by adrielldagasuan** [comment]
Yep. Our builds are failing because we install salt when provisioning using packer.

**Comment by StevenPaugh** [comment]
Also affected. Failing builds due to https://bootstrap.saltproject.io/

**Comment by dmurphy18** [comment]
@neopointer @adrielldagasuan @StevenPaugh Salt is undergoing infrastructural changes, that are only partially complete. Please bare with us as these changes occur, see https://saltproject.io/blog/upcoming-salt-project-docs-and-repo-migration/

**Comment by adrielldagasuan** [comment]
@dmurphy18 the install script from bootstrap seems incorrect now. I wouldn't have thought it will be affected by this infra change but what do you think?

```
Installing Salt with command sudo sh /tmp/install_salt.sh -D -s 10 -i base-ami stable 3006
Downloading saltstack bootstrap to /tmp/install_salt.sh
/tmp/install_salt.sh: 2: Syntax error: newline unexpected
```

Update:

Maybe it is affected as it doesn't redirect anymore.
```
curl -L https://bootstrap.saltproject.io
<meta http-equiv="refresh" content="0; url=./bootstrap-salt.sh" />
```

**Comment by AGirin** [comment]
Same issue here. Builds stopped working and are still not working. Same error as above:

curl -L https://bootstrap.saltproject.io
<meta http-equiv="refresh" content="0; url=./bootstrap-salt.sh" />

```
/root/bootstrap-salt.sh: line 1: `<meta http-equiv="refresh" content="0; url=./bootstrap-salt.sh" />'
```

**Comment by AGirin** [comment]
> curl -L https://bootstrap.saltproject.io

I fixed it with this: 
```
curl -o /root/bootstrap-salt.sh -L https://bootstrap.saltproject.io/bootstrap-salt.sh
```

**Comment by dmurphy18** [comment]
Please see https://saltproject.io/blog/salt-bootstrap-breakage/

**Comment by ScriptAutomate** [comment]
Certificate issue has been resolved:
- https://saltproject.io/blog/upcoming-salt-project-docs-and-repo-migration/

Along with next steps on a new location for downloading the bootstrap scripts:
- https://saltproject.io/blog/salt-bootstrap-breakage-part-2/

`salt-bootstrap` itself, though, still needs updating to work with the new `packages.broadcom.com` repo hosting, layout, and package management layer of version pinning (apt, dnf), etc.
- https://saltproject.io/blog/salt-project-package-repo-migration-and-guidance/

A new issue has been made for `salt-bootstrap` fixes in relation to the new `packages.broadcom.com` repo hosting:
- https://github.com/saltstack/salt-bootstrap/issues/2027

Closing this issue since certificates were resolved after DNS propagation and Let's Encrypt automation eventually completed.
