### ISSUE TITLE
salt-minion 3006.1 keeps installing 3006.9 ever since broadcom repo updates (CentOS 7)

### ISSUE THREAD

**Issue by IanMann-CVET** [saltstack/salt-bootstrap#2034]
### Description of Issue/Question

I followed the migration instructions and updated the URLs below. 

I've updated the URLs but its installing 3006.9 when I'm specifying 3006.1. After it installs and I do a salt --version I'm getting 3006.9 (Sulfur).

URL's I've updated to. They look correct to me. But clearly I'm missing something because I'm getting a version miss-match. 
sudo rpm --import https://packages.broadcom.com/artifactory/api/security/keypair/SaltProjectKey/public
curl -fsSL https://github.com/saltstack/salt-install-guide/releases/latest/download/salt.repo | sudo tee /etc/yum.repos.d/salt.repo
sudo yum clean expire-cache
sudo yum -y install salt-minion-3006.1

### Setup
OS is centos 7.

**Comment by asami1994** [comment]
Hi @IanMann-CVET ! I tested the installation on a CentOS 7 container following the provided steps and confirmed that salt-minion version `3006.1` installs as expected for me. Here are a few things you might want to check or try to pinpoint the discrepancy:

**Cache and Repository Cleanup:** Sometimes, yum can pull a cached or different version than specified. Run the following commands before installation to ensure a fresh pull:
```
sudo yum clean all
sudo yum clean expire-cache
```
**Repository Configuration:** Double-check that the repository URL in `/etc/yum.repos.d/salt.repo` exactly matches the latest instructions. If there’s an issue with the repo file itself, `yum` might pull the latest available version instead of the one specified.

**Package Metadata:** Ensure the repository metadata is up-to-date. Running `sudo yum makecache fast` after setting up the repository can help confirm it pulls the correct metadata and package versions.

Follow https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/linux-rpm.html for further help.

**Comment by IanMann-CVET** [comment]
This is what I'm showing for the /etc/yum.repos.d/salt.repo 

The only thing I can think of is salt-repo-3006-lts isn't what I want.

[salt-repo-3006-lts]
name=Salt Repo for Salt v3006 LTS
baseurl=https://packages.broadcom.com/artifactory/saltproject-rpm/
skip_if_unavailable=True
priority=10
enabled=1
enabled_metadata=1
gpgcheck=1
exclude=*3007* *3008* *3009* *3010*
gpgkey=https://packages.broadcom.com/artifactory/api/security/keypair/SaltProjectKey/public

[salt-repo-3007-sts]
name=Salt Repo for Salt v3007 STS
baseurl=https://packages.broadcom.com/artifactory/saltproject-rpm/
skip_if_unavailable=True
priority=10
enabled=0
enabled_metadata=1
gpgcheck=1
exclude=*3006* *3008* *3009* *3010*
gpgkey=https://packages.broadcom.com/artifactory/api/security/keypair/SaltProjectKey/public

[salt-repo-latest]
name=Salt Repo for Salt LATEST release
baseurl=https://packages.broadcom.com/artifactory/saltproject-rpm/
skip_if_unavailable=True
priority=10
enabled=0
enabled_metadata=1
gpgcheck=1
gpgkey=https://packages.broadcom.com/artifactory/api/security/keypair/SaltProjectKey/public

**Comment by ScriptAutomate** [comment]
@IanMann-CVET 

When testing our repo file configurations on [Salt supported operating systems](https://docs.saltproject.io/salt/install-guide/en/latest/topics/salt-supported-operating-systems.html) (Rocky Linux 8 and 9, CentOS Stream 9, etc.), via the new [Salt Install Guide: Linux (RPM)](https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/linux-rpm.html) install directions, these configurations and install directions work as expected.

Closing this ticket as CentOS 7 is EOL, and no longer supported by Salt Project.

**Comment by IanMann-CVET** [comment]
yeah CentOS 7 is EOL. I believe I found a solution by setting a version lock. Thank you for your time.
