### ISSUE TITLE
salt dependencies not auto installed

### ISSUE THREAD

**Issue by alpana17** [saltstack/salt-bootstrap#2064]
I am installing salt==3006.1 via pip
Earlier, it used to install all its dependencies on its own.

But just seen that it is not installing all dependencies like looseversion, msgpack

**Comment by dmurphy18** [comment]
@alpana17 Can you try it with 3006.8 or 3006.9, that is a very early version of 3006.  Also just released v2024.12.09 of the bootstrap scripts, please use that later version.

Also the above does not appear to be part of a bootstrap-salt.sh command, are you sure you have the correct repository, and please use the full command used on the command line

**Comment by dmurphy18** [comment]
@alpana17 Closing this since it is related to salt and not salt-bootstrap, please open the issue against repository https://github.com/saltstack/salt, and please carefully fill out the template, given complete information (for example: complete command line) and the OS on which you are performing this operation.

Otherwise your issue will be rejected if insufficient information is supplied in order to duplicate the problem
