### ISSUE TITLE
Bootstrap does not install git-core (on stable), or gitpython (on stable or git).

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt-bootstrap#245]
It was noted by xuru in the IRC today that the bootstrap script is not installing git-core/gitpython when performing an installation using the stable option (or no option), this makes it so you are unable to use gitfs. If calling the script using the git option it does install git-core, however gitpython is still not installed. Is this by design?

**Comment by xuru** [comment]
When using the install type of 'stable' I have to do the following in order to have gitfs working (from the vagrant file):
  config.vm.provision :shell, :inline => "sudo apt-get install git-core"
  config.vm.provision :shell, :inline => "sudo apt-get install python-setuptools"
  config.vm.provision :shell, :inline => "sudo easy_install GitPython"

Seems like we can can install these packages by default.  The only concern would be any security issues installing git on a production system.  However, we could add an argument to have it install git tools...

**Comment by s0undt3ch** [comment]
The bootstrap script only installs what's required for salt to run, ie, it's hard dependencies.
- Git, although it's not a hard dependency to install Salt, it **is** required if you're trying to install salt from git
- Git Python is not a hard dependency to Salt, as such, it won't be installed

I know it's not what you were after but, you can install those packages once salt is installed using salt.

I'm closing as _won't fix_, at least for now.

**Comment by v6** [comment]
// , This does not imply to start out with some sort of shell provisioning, because maybe one could make the first few salt states that run install Git and Python prerequisites for the other states?
