### ISSUE TITLE
Version management via bootstrap & git-- /etc/salt/* being overwritten

### ISSUE THREAD

**Issue by chrisblossom** [saltstack/salt-bootstrap#254]
It would be great if we could use bootstrap to manage salt-versions installed via git. The biggest issue stopping this that I've found is that the bootstrap script overwrites all config files in /etc/salt/*.

If there was an option to either upgrade and not to overwrite these files, or some logic to see if the files already exist, or even to skip already-installed dependancies, that would make upgrading/downgrading possible using bootstrap.

It is very possible there is a better solution to manage salt install versions via git that I am not aware of. If there is, please advise.

**Comment by s0undt3ch** [comment]
Well, let's start answering :smile: 

The script does not overwrite any configuration files unless you pass `-F` to it, if it does, it's a bug.
However, your distribution's package manager might overwrite those files and there's nothing much we can do about that.

The script is a one time execution script, once executed, it no longer knows what it did, it can only do it again.
Tracking already installed dependencies is behind what this script can and should do.

So, regarding upgrades/downgrades, the script _might_ only upgrade some packages if it's needed to install salt. Downgrading, is not on this script's scope.
If however, you're trying to install different versions of salt, the only option you might have is using git tags since most, if not all, distribution package managers only keep latest stable release in their repositories.

To install a specific salt version you can pass `git v0.16.4` or `git v0.17.1` which are [salt releases](https://github.com/saltstack/salt/releases). Do note that if you upgrade or downgrade salt using a git tag, the script does not know, and will not try to find out, if salt was previously installed on that system, it simply overwrites the previous installation(not previous configuration files).

I hope this helps.

**Comment by s0undt3ch** [comment]
Closing as "fixed" as no additional input was added.
