### ISSUE TITLE
Failing bootstrap with -U and grub update

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt-bootstrap#277]
Running this via Vagrant on a clean precise64 results in massive screen corruption and a stalling deploy.

**Comment by s0undt3ch** [comment]
Full debug output(`-D`), possible?

**Comment by syphernl** [comment]
Done ,but that doesn't show anything helpful. The updates may need to be tweaked a little to use non interactive, confdef & confold.

**Comment by s0undt3ch** [comment]
Please include gere or paste the debug output somewhere and the link here.

**Comment by syphernl** [comment]
Output is available here: http://pastebin.com/v3Dscp28

**Comment by s0undt3ch** [comment]
Sorry for the huge amount of time it took me to get to this ticket.

This was a problem with Ubuntu's upgrade process, not related to the script's action, ie, the script only failed because the upgrade process also failed.

Our upgrade command is "apt-get upgrade -y -o DPkg::Options::=--force-confold", do you suggest any improvement to that?

Closing as I've just bootstrapped a Rackspace Ubuntu 12.04 image(upgrading it) without any problems.
Please reopen if need be.
