### ISSUE TITLE
EL6 - bootstrap fails to address semanage dependency on @Core builds

### ISSUE THREAD

**Issue by ferricoxide** [saltstack/salt-bootstrap#531]
**Background:** In our environment, our baseline deployments use the "Core" installation profile, only. Running the Salt bootstrap takes care of most of the Salt-required RPMs that are not part of "Core". However, the script does not currently seem to resolve the dependencies for the SELinux Salt modules.

**Symptom:** When running recipes that require the 'selinux.mode' module, SLS will fail with a "function not available" error.

**Fix:** Installation of `libsemanage-python` and/or `policycoreutils-python` ensures all of the requisite Python handlers for SELinux and related RPMs are installed. the full list that was installed by the `yum` job was:
- policycoreutils-python
- libsemanage-python
- libselinux-python
- setools-libs
- setools-libs-python
- audit-libs-python
- libcgroup

**Comment by s0undt3ch** [comment]
What type of bootstrap do you use? Git? Or system packages?

**Comment by ferricoxide** [comment]
Sorry. I currently use the `wget -O - https://bootstrap.saltstack.com | sh` method to do my setup.

**Comment by s0undt3ch** [comment]
Ok. Thanks!

@terminalmage is this something we can address on Salt's RPMs?

**Comment by vutny** [comment]
@ferricoxide I guess there are many-many packages need to be installed for all modules and states to work out the box after bootstrap. It's better to manage such dependencies with Salt (add/enable necessary repos, install specific versions and so on). Or as alternative you can use `-p` option:

```
    -p  Extra-package to install while installing salt dependencies. One package
        per -p flag. You're responsible for providing the proper package name.
```

I think it should be closed.

**Comment by ferricoxide** [comment]
For a properly constructed RPM of the salt-packages, there should probably be a `requires:` for the two missing packages (`libsemanage-python` and/or `policycoreutils-python`) in the SPEC file. Yum will take care to resolve the sub-dependencies associated with the `libsemanage-python` and/or `policycoreutils-python` packages.

**Comment by vutny** [comment]
@ferricoxide I just wanted to say that SELinux packages are not the hard requirements for Salt to start up, run and perform its main job. To unlock some modules functionality, you need to install additional software.
For example, to make [git module](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.git.html) work, you obviously should install `git` package on the target system before. But this cannot be a reason to add `git` in the `salt` rpm spec.
Such modularity is the one of Salt's powers, and that's why we love it :-)

**Comment by ferricoxide** [comment]
What I'm saying is that one of the beauties of RPM/yum is that dependencies are generally auto-resolved. If packages are properly constructed, one never runs into an issue where they go to execute a given function within packaged and that function fails due to an unsatisfied dependency. That's why system owners love RPM/yum.

I can understand leaving dependency-resolution to the system owner if you're only providing SaltStack in the form of a tarball, but when you provide it in the form of an RPM, it's sort of a given that the RPM maintainer isn't leaving the system owner in the lurch for dependency-tracking.

**Comment by vutny** [comment]
@ferricoxide Yeah, you're totally right about that the dependencies resolution is the package manager software job.
The problem here is that Salt rpm just cannot require all packages to make all available modules to work out of the box (not just `selinux`). Mostly because there are many software which Salt is able to manage, but the packages are not the part of RHEL/CentOS/EPEL/Fedora repos, for example: [esxi state](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.esxi.html).

Resolving dependencies with `yum` would be possible if any "non-core" modules will be distributed as separate packages, similar to Nagios plugin packages:

```
# repoquery -a --qf "%{name}" | grep nagios-plugin | head
nagios-plugins
nagios-plugins-all
nagios-plugins-apt
nagios-plugins-bacula
nagios-plugins-bonding
nagios-plugins-breeze
nagios-plugins-by_ssh
nagios-plugins-check-updates
nagios-plugins-cluster
nagios-plugins-dbi
```

As for now, single `salt` rpm package includes 99% of projects code.

Another part, in RPM world there are only **hard** requirements: you need to install all packages even if some of them will never be used.
`deb` packages are more flexible with two optional dependency layers: _Recommends_ and _Suggests_. This way administrator can choose whatever to install everything possible, or just minimal required packages to get useful software.

Anyhow, this issue is not related to the bootstrap script.
SaltStack has a dedicated project for producing Salt packages: https://github.com/saltstack/salt-pack.
They really welcome any valuable contribution.

**Comment by ferricoxide** [comment]
No worries. At the time I opened the bug, I was using the `curl`bootstrap script. Recently switched to using the Salt RPM method that includes the Salt-specific repos (rather than the EPEL ones).

At this point, it's mostly wishlisting. While it's easy enough for me to put in my documentation to our ops team and the self-service users to "do X, Y and Z" (where "Z" is the "install the Salt RPMs" step), it becomes an article of faith that they'll have paid attention and satisfied "X" and "Y". Trying to cut down on the likelihood of them coming to me, griping that things blew up because they only paid attetion to "Z". :)

**Comment by vutny** [comment]
@ferricoxide By the way, recent _develop_ version of `bootstrap-salt.sh` (fetched from https://bootstrap.saltstack.com/develop) is doing all this stuff for you: configure Salt corporate repositories and install latest stable packages from there (and even additional ones as I mentioned before) with shell one-liner. Check it out, that should save you from additional manual work.
Few things should be fixed and I hope it will became "stable" soon enough.

Another matter, currently I'm working on the project to make bootstrapping even more automated and reliable... But not sure when I could release it, still on the early stage of development.

So... Could you be so kind to close the issue?

**Comment by ferricoxide** [comment]
Oop. Sorry. Thought only you guys could close (or otherwise modify issues) once opened.
