### ISSUE TITLE
2015.8 salt bootstrap failing to install salt on Ubuntu 14.04 and 12.04

### ISSUE THREAD

**Issue by ssgward** [saltstack/salt-bootstrap#629]
2015.8 salt bootstrap failing to install salt on Ubuntu 14.04 and 12.04.

EL 6.5 / 7.0 salt bootstrap installs are working fine.

The bootstrap failure on Ubuntu states that tornado >= 4.0 needs to be present and is not. 

Tornado 2.1 is on the EL 7.0 system prior to bootstrap. Tornado is not on the EL 6.5 system prior to bootstrap. Tornado 4.1-3 is on the EL systems after bootstrap. Tornado is not on any of the Ubuntu systems prior to bootstrap nor after.

**Comment by s0undt3ch** [comment]
You need to pass `-P` in order to install tornado from PyPi, as you probably saw on the error message.
There ain't a recent enough tornado package to use that's why the bootstrap tries to install it from PyPi but it will only succeed if you pass `-P`.

**Comment by s0undt3ch** [comment]
Removed the bug label as this is not a bug, it's expected behavior.

**Comment by s0undt3ch** [comment]
Until there's not a recent enough packaged tornado, we'll have to enforce the installation of it using `pip`.

**Comment by s0undt3ch** [comment]
Just to confirm, we're talking about a git based installation?

**Comment by s0undt3ch** [comment]
I believe this was while running the latest stable version of the bootstrap script which in fact had a [quoting issue](https://github.com/saltstack/salt-bootstrap/commit/81534c11c20f50277e4c92e393ac66c2fc042e24) which prevented tornado to be installed even after passing `-P`.

Using the development version of the script while passing `-P` properly installs salt and it's required tornado dependency.

However, once we have a stable release of salt v2015.8.0 we will have problems again since the stable installation process is not using the pip based solution.... Keeping this open.

**Comment by s0undt3ch** [comment]
https://github.com/saltstack/salt-bootstrap/commit/0b5524317258a715f2ceb4c69e89530f15bfe05f will address the future v2015.8.xx stable releases issue mentioned above, still using `pip` until we can install a recent enough tornado package from at least a PPA.
