### ISSUE TITLE
Ubuntu 12.04 (and maybe 12.x?): apt-get installing python-requests causes digital_ocean_v2 to fail with "[ERROR ] Failed to get the output of 'digital_ocean.avail_sizes()': 'Response' object has no attribute 'text'"

### ISSUE THREAD

**Issue by jf** [saltstack/salt-bootstrap#630]
As per subject. I believe the line in question is https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L1773. Please see https://github.com/saltstack/salt/issues/25597 for more info.

The problem is that apt-get installs `python-requests` 0.8.2 on 12.04, and in this version of `requests`, the `request` object does not have that attribute `text`. Whereas a more up-to-date version of `requests` does.

**Comment by s0undt3ch** [comment]
What version of the bootstrap script are you using?

**Comment by s0undt3ch** [comment]
What kind of installation were you trying to do? Stable installation? Git based installation?

**Comment by s0undt3ch** [comment]
Fixed in latest stable release

**Comment by dmick** [comment]
Why wouldn't this be fixed in the salt sources rather than opening the huge can of dependency worms of replacing a standard package and its dependencies with a ppa?

It's pretty easy to look for the text attribute on the Response object and cope if it's not present, and be compatible with both styles of python-requests.  Puzzled at the choice.

(and it's still not fixed, even after this, and 631, and 632; there are still errors bootstrapping on Precise.)

**Comment by jf** [comment]
Feel free to enlighten me here, guys, but... who is this Chris Lea, and how is he involved?

**Comment by dmick** [comment]
all I know is he's some guy that maintains PPAs, and he's involved because he has a later revision of python-requests.  he wouldn't be, if the fix had been made to the salt source.

**Comment by jf** [comment]
Gotcha, Dan. Well now if he simply goes about doing his stuff without an eye to Salt....
