### ISSUE TITLE
Problems with bootstrap install on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by cryptolukas** [saltstack/salt-bootstrap#635]
Hi  @all,

I try to install salt/salt-master. I get in contact with many problems.

This command get in problems:

sudo sh install_salt.sh git develop
- ERROR: You need to allow pip based installations (-P) in order to install the python package 'tornado >= 4.0'

With this command it works:
sudo sh install_salt.sh -P git

I do not understand  why need to attach git at the end?

Can anyone support me with this error? How can I solve it? Why I had so much problems with a standard salt installation? Do I make many failures with the install way?

**Comment by s0undt3ch** [comment]
Your initial  command was:

```
sudo sh install_salt.sh git develop
```

The error told you to include `-P`. So your initial command would become:

```
sudo sh install_salt.sh -P git develop
```

**Comment by cryptolukas** [comment]
here  it works better for beginners

http://docs.saltstack.com/en/latest/topics/installation/ubuntu.html

**Comment by HeisenbergTP** [comment]
You can close this all you want but it doesn't solve the actual problem.

**Comment by jchv** [comment]
As of 20 hours ago, this infuriating problem actually is finally solved. It's not on the bootstrap /develop version, so you'll need to pull it from GitHub, something like this:

``` bash
sudo curl -o /etc/salt/cloud.deploy.d/bootstrap-salt.sh -L https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh
sudo curl -o /usr/lib/python2.7/dist-packages/salt/cloud/deploy/bootstrap-salt.sh -L https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh
```

After that, remove your `script_args` from your cloud provider if you're using Salt-cloud and you should be all good. If you're not, just run the script with no arguments and you should have the very latest version, no Pip dependencies.

After many wasted hours of both actual time and server time, I am very relieved to finally have this one solved. I greatly appreciate all of the work that goes into Salt and its massive breadth but can't help but feel more processes need to be put into place to ensure that stable releases at least work as expected in common cases. Of course, Salt is not entirely to blame, because dependencies like boto have caused me excruciating headaches as well despite their seemingly good track records. Anyway, I know an issue comment is not an ideal place to vent, but at least I'm glad to say this very agitating bug is finally behind us all.

**Comment by jfindlay** [comment]
@johnwchadwick, I have checked this morning that https://bootstrap.saltstack.com/develop and https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh both point to the same script, being that available at the HEAD of the salt-bootstrap/develop branch.  I do not know how this gets updated, but I assumed it was always pointing to the head of the branch.  @s0undt3ch will very likely know more than I about this.

I have tested ubuntu 12.04 and 14.04 multiple times with the changes now in develop (#674) and `-P` was not required in any case.

**Comment by s0undt3ch** [comment]
We've had some SSL certificate issues in  the past when we redirected to GitHub to get the latest HEAD, because of that, we're now hosting the copies of the script behind our own servers. Right now, this is a semi-manual process, hence the delay, specially because we had the weekend in between.
In the future, we want to fully automate the process to make sure that situations like this one don't happen again.
We're sorry for the inconvenience caused.

/cc @UtahDave

**Comment by jchv** [comment]
Just to be clear, `/develop` not being automatically up to date isn't much of an inconvenience to me personally. Almost everything I said was with regards to #674 because this issue is the first one that you come across when Googling the error message caused by it and I wanted to make sure there were clear instructions on solving the problem somewhere here. (But of course thanks for fixing `/develop` nonetheless.)

One thing I do wish to ask is when develop is merged into stable. Would that coincide with Salt releases?

**Comment by jfindlay** [comment]
@LukasDoe, we are about to make a new salt-bootstrap release, which corresponds to merging bootstrap-salt.sh into the salt codebase.  The next salt release will come out in a few weeks and will definitely include this new bootstrap release.

**Comment by jakehilton** [comment]
I'm also having issues.. and as reccomended above I use the "ubuntu installation for beginners".. I get the following error:

# apt-get install salt-master

Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 salt-master : Depends: sysv-rc (>= 2.88dsf-24) but 2.88dsf-13.10ubuntu11.1 is to be installed or
                        file-rc (>= 0.8.16) but it is not installable
               Depends: salt-common (= 2015.8.1+ds-1) but it is not going to be installed
               Depends: python-crypto (>= 2.6.1) but 2.4.1-1ubuntu0.1 is to be installed
               Depends: python-msgpack but it is not installable
               Depends: python-zmq (>= 13.1.0) but it is not going to be installed
               Recommends: python-git but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

So the referenced installation fails miserably unfortunately. This was run on a fresh install of 14.04.3.

**Comment by dmurphy18** [comment]
@jakehilton Can you post the output of running 'apt-cache policy salt-master' and 'apt-cache policy python-msgpack'.  The problem is due to python-msgpack is not installable, but also python-crypto should be 2.6.1 or higher, which it is not here.
The repository with the latest salt-master and it's dependencies for Ubuntu 14.04 is available from repo.saltstack.com.

**Comment by jakehilton** [comment]
Well I worked through that initial error.. whoever had setup the server had some weird entries in the sources.list. So I blew it away and started it from scratch.

So now when I run the install I get the following error:

`Unpacking salt-common (2015.8.1+ds-1) ...
dpkg: error processing archive /var/cache/apt/archives/salt-common_2015.8.1+ds-1_all.deb (--unpack):
 trying to overwrite '/var/log', which is also in package sysstat 10.2.0-1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Selecting previously unselected package salt-master.
Preparing to unpack .../salt-master_2015.8.1+ds-1_all.deb ...
Unpacking salt-master (2015.8.1+ds-1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Errors were encountered while processing:
 /var/cache/apt/archives/salt-common_2015.8.1+ds-1_all.deb
E: Directory '/var/log/apt/' missing
E: Sub-process /usr/bin/dpkg returned an error code (1)`

My output of apt-cache policy salt-master is:
`# apt-cache policy salt-master
salt-master:
  Installed: 2015.8.1+ds-1
  Candidate: 2015.8.1+ds-1
  Version table:
 *** 2015.8.1+ds-1 0
        500 http://repo.saltstack.com/apt/ubuntu/ubuntu14/latest/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     0.17.5+ds-1 0
        500 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages`

Thank you for the help.

**Comment by jakehilton** [comment]
I think I've worked it out.. will report back.

**Comment by syedaali** [comment]
When I attempt to deploy an instance using salt-cloud using 'salt-cloud --profile=ec2 my instance', I am getting an error: \* ERROR: You need to allow pip based installations (-P) in order to install the python package 'tornado >= 4.0'. This error occurs after the instance is created in AWS and salt-cloud tries to install salt-minion.

I am using the below versions. I guess I need to specify -P in my /etc/salt/cloud.profiles.d/<name>, what is the key though? Is it bootstrap_options = -P?

# salt --versions

Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-66-generic
         system: Ubuntu 14.04 trusty

**Comment by syedaali** [comment]
I found the options:

script: bootstrap-salt
script_args: -P

**Comment by jakehilton** [comment]
All is working for me now. Thank you.
