### ISSUE TITLE
Flag for aptitude full-upgrade?

### ISSUE THREAD

**Issue by mafrosis** [saltstack/salt-bootstrap#66]
Some discussion at work raised the idea of running a full package upgrade on a newly minted server. (Amazon's AMIs are inevitably a little out of date at creation).

What do you think to adding a flag to the bootstrap script to do this?

This may well be classed as out of the scope of salt-bootstrap, but I thought I'd ask the question..

**Comment by s0undt3ch** [comment]
Well, I do think that this is outside of the script's scope, and, once you have a minion running, you can always run a full upgrade through it.

Is there anything which will make the bootstrap script fail if the system is not fully upgraded?
If there is, then this falls into the script's scope because it should be able to properly install salt on supported distributions.

Am I not seeing a bigger picture?

**Comment by mafrosis** [comment]
No that's all there is to it really- I very nearly didn't post the above as I expected this to be your response. And I agree! We'll do a package upgrade via salt instead.
