### ISSUE TITLE
[Feature Request] install Extra Packages first

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt-bootstrap#694]
https://github.com/saltstack/salt/issues/29094

This would help allow getting around this issue, for rhel 5 at least, so that you can specify the correct package that is missing in the dependency chain and everything can work

**Comment by vutny** [comment]
@gtmanfred This is interesting, but I personally think that doing such feature especially to get a workaround for other issues is generally a bad practice.
If you able to bootstrap a machine, it means that you're able to login on it and have enough privileges to install anything you want prior to running bootstrap script as a workaround for any pending issues.

**Comment by vutny** [comment]
@gtmanfred I believe saltstack/salt#29094 is already fixed with latest repo updates and bootstrap develop branch. I've got everything work smoothly on both RHEL5 and RHEL7:
- https://gist.github.com/vutny/d710993c13bca9f53fba
- https://gist.github.com/vutny/54a2d09b2b8f8f8b6fd5

Does it work for you? Thanks for any feedback!

**Comment by gtmanfred** [comment]
I am in Atlanta this week, I will check them when I get back to San Antonio
next week.

**Comment by vutny** [comment]
@gtmanfred Have you had a chance check your issues on RHEL systems with latest bootsrap?
I think this issue could be closed anyhow and reopened if you'll really demand this feature.

**Comment by jfindlay** [comment]
@gtmanfred, also be aware that https://bootstrap.saltstack.com/develop is updated manually (@utahdave is doing this right now).
