### ISSUE TITLE
Feature suggestion: Flag to specify custom repository URL

### ISSUE THREAD

**Issue by timcharper** [saltstack/salt-bootstrap#728]
Since the debian repo lacks a way to lock to a consistent major version, I'd like to snapshot a version of the repository and use it (occasionally have been burned by surprise upgrades).

There doesn't seem to be a way to specify that a different apt repository should be used. I'd like to add the option but wanted to ask for opinions on it, first.

**Comment by jfindlay** [comment]
@timcharper, with the merge of #797, you should be able to install a specific version (from packages!) on debian 8 from repo.saltstack.com with `stable 2015.8.8`.

**Comment by timcharper** [comment]
Dancing cartwheels! Great news, @jfindlay !

**Comment by timcharper** [comment]
oh, the request was for something else; leaving open.

**Comment by rallytime** [comment]
@timcharper The `-R` option was recently added to support something like this for RHEL/CentOS. This same philosophy can, and should, be expanded to other distros, but I wanted to check with you to see if that is the right direction you were thinking on this. 

Basically the the help docs for `-R` look like this:

```
-R  Specify a custom repository URL. Assumes the custom repository URL
        points to a repository that mirrors Salt packages located at
        repo.saltstack.com. The option passed with -R replaces the
        "repo.saltstack.com". If -R is passed, -r is also set. Currently only
        works on CentOS/RHEL based distributions.
```

Where `-r` disables all other other repository configuration.

These two options were added to address #710, but this request feels similar and could be fixed in the same way.

**Comment by rallytime** [comment]
I am fairly certain that the `-R` option is the best way to tackle this. This is supported for RHEL distros already, and support was just added today for Debian/Ubuntu in #1045. 

Since we haven't heard back here, and the `-R` option should work for this, I am going to close this. We can continue the conversation as needed, and reopen if necessary. Thanks!
