### ISSUE TITLE
error running stable script on OEL 5

### ISSUE THREAD

**Issue by jasontrodd** [saltstack/salt-bootstrap#894]
When running bootstrap_salt.sh downloaded from bootstrap.saltstack.com on an OEL 5 system an error is thrown:

/tmp/bootstrap_salt.sh: line 25: *: unbound variable

The last successful provisioning I had with downloading the script was running the 2016.05.11 version.

I'm running the script with no arguments as per https://docs.saltstack.com/en/latest/topics/tutorials/salt_bootstrap.html#install-using-wget.

**Comment by vutny** [comment]
@jasontrodd I've fixed it in #895, welcome to test.

Actually it affects all flavors of RHEL/CentOS 5 systems with bash 3.2. FYI @rallytime

**Comment by jasontrodd** [comment]
Hi @vutny 

I've tested your changes in my environment and the installs are working properly now.  Thanks!!

How long do changes like this normally take to get merged into stable?

**Comment by rallytime** [comment]
Thanks for grabbing this @vutny - I saw this yesterday and meant to grab it today, but you beat me to it! :D

@jasontrodd Apologies for the breakage. The changes won't get merged into stable until we are ready to do another release. In the meant time, you can use the wget method to pull down the script on the develop branch from this commit: 5d9ede854d3e00fbd5d71b6624fe7acd59939477.

Nothing has been added to the develop branch since the last stable release, so you can pull down from that commit which has the fix. The raw file link is here: https://raw.githubusercontent.com/saltstack/salt-bootstrap/5d9ede854d3e00fbd5d71b6624fe7acd59939477/bootstrap-salt.sh

**Comment by jasontrodd** [comment]
Thanks @vutny @rallytime for the quick pickup!!!

Unfortunately my process for grabbing this script involves requesting the script directly from bootstrap.saltstack.com and the scripts are a pain to change (VMware vCloud Director templates).  I’m working through a way to direct wget to a local web server where I can redirect to which ever branch/rev is appropriate.  It will still require a change, but just one and then we’ll be all set.

Thanks again!
