### ISSUE TITLE
Size mismatch errors when using apt-cacher

### ISSUE THREAD

**Issue by ghost** [saltstack/salt-bootstrap#961]
### Description of Issue/Question

Hi,

I'm using Ubuntu apt-cacher to decrease network traffic and prevent all servers having internet access.
But that cause a Size mismatch error on updating different versions of salt packages.

apt-cacher isn't storing source information of the packages. And because the salt packages for all versions (12.04, 14.04 and 16.04) have the same name (e.g salt-common_2016.3.3+ds-1_all.deb) it tries to provide the last one for a request. But they have different size (and content) which cause error for Apt.

I think the package name should contain either the version or codename of the target Ubuntu.
### Setup

Different versions of Ubuntu LTS servers are connected to the internet through a common Apt-cacher server.
### Steps to Reproduce Issue

First install/update salt on a Ubuntu 12.04 and then installing on a different Ubuntu version it'll fail with Size mismatch error.
### Versions and Systems

latest, 2016.3.3

**Comment by thatch45** [comment]
Yes, the package should contain the name as well, we will look into it

**Comment by rallytime** [comment]
I think this issue is more of a [salt-pack](https://github.com/saltstack/salt-pack/) issue rather than a salt-bootstrap issue, since all bootstrap is doing is installing the packages that we're building via salt-pack and hosting on repo.saltstack.com.

I have opened https://github.com/saltstack/salt-pack/issues/147 in the salt-pack repo to replace this issue. @KundK Please see the new issue to track it's progress. I have `@` mentioned you in the new issue so you can see updates. I'm closing this issue for now. Thanks!
