### ISSUE TITLE
RFE: Support rpm/deb package download only operation

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt-bootstrap#968]
### Description of Issue/Question

For some minions sitting behind firewall that have minion ports opened but not http/https connection to the internet, this download only will all them to have smooth upgrade.
### Setup

This is a RFE to add this new feature. 
### Steps to Reproduce Issue

```
#download all the latest minion rpm/deb package to temp directory
bootstrap_salt.sh --downloadonly --out=/tmp 

# then we can copy the pkg file to minions inside firewall and run local pkg install using package managers.
```
### Versions and Systems

./bootstrap_salt.sh -- Version 2016.08.16

**Comment by rallytime** [comment]
@tjyang Would the -R option work for you? This was added somewhat recently and might be a good work around here. Note that only CentOS/RHEL is supported here, but other distros could be added as needed.

**Comment by tjyang** [comment]
--downloadonly will be still needed for machine without salt-minion installed.

" -R  Specify a custom repository URL. "  Looks like a way to upgrade  when salt-minion got installed already.

One would have to create a file based local repo using existing cp.\* command by  copy the content of  repo.saltack.com into a minion's file system and create a repo like "file:///.." in  following for Oracle Linux example.

```
[OL63]
name=Oracle Linux 6.3 x86_64
baseurl=file:///var/OSimage/OL6.3_x86_64
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY
gpgcheck=1 
enabled=1 
```

R1: https://docs.oracle.com/cd/E37670_01/E37355/html/ol_create_repo.html

**Comment by rallytime** [comment]
> Looks like a way to upgrade when salt-minion got installed already.

The -R option doesn't mean that the minion is already installed. It means that if you pass a custom repository URL where the files from repo.saltstack.com exist, then you could point to this server instead of repo.saltstack.com.

You would have to create a local repo _somewhere_ . This option is to aid in setups where outside access is not possible, but you could still run bootstrap like normal and use package managers like normal, but point it at your own repo which has used something like `rsync` to get the package files from repo.saltstack.com. Does that help?

Note that this option only works for CentOS/RHEL-based installs. However this could be expanded to debian/ubuntu.

**Comment by rallytime** [comment]
@tjyang ^ I just wanted to expand on how -R works for now, since that is an option that is already available. I would have to think on the "download only" option.

**Comment by rallytime** [comment]
@s0undt3ch You might have some ideas here as well.

**Comment by s0undt3ch** [comment]
The `rsync` plus `-R` seem to be the right options.

Installing from locally downloaded packages withough a repo serving them will most likely require its own set of install functions, and then we have to account for packages which include version information on the name and we would end up quite often out of sync....

**Comment by rallytime** [comment]
@s0undt3ch Yeah, I agree. Perhaps the feature request here then should just be to expand the `-R` functionality to work with Debian/Ubuntu (since only RedHat-based distros are supported currently).

**Comment by rallytime** [comment]
I have added support for Debian/Ubuntu for the `-R` option in #1045.
