### ISSUE TITLE
Ubuntu 16.10 Unsupported

### ISSUE THREAD

**Issue by forty8bits** [saltstack/salt-bootstrap#976]
### Description of Issue/Question

Ubuntu 16.10 was released earlier this month; salt-bootstrap (understandably) fails to run successfully, but support should likely be added.
### Steps to Reproduce Issue

Simply run `curl -L https://bootstrap.saltstack.com | sudo sh` on a fresh install of any variant of Ubuntu 16.10 (Ubuntu Mate in my case).
### Versions and Systems

Output of `sudo find /etc/ -name \*-release -print -exec cat {} \;`:

```
/etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.10
DISTRIB_CODENAME=yakkety
DISTRIB_DESCRIPTION="Ubuntu 16.10"
/etc/os-release
NAME="Ubuntu"
VERSION="16.10 (Yakkety Yak)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.10"
VERSION_ID="16.10"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="http://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=yakkety
UBUNTU_CODENAME=yakkety
/etc/update-manager/meta-release
# default location for the meta-release file

[METARELEASE]
URI = http://changelogs.ubuntu.com/meta-release
URI_LTS = http://changelogs.ubuntu.com/meta-release-lts
URI_UNSTABLE_POSTFIX = -development
URI_PROPOSED_POSTFIX = -proposed
```

Output of `command lsb_release -a`:

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.10
Release:        16.10
Codename:       yakkety
```

**Comment by rallytime** [comment]
Ah, good reminder @forty8bits! Thanks!

**Comment by rallytime** [comment]
@forty8bits The installation for 16.10 has been fixed in #998. There is some clean up to do, as mentioned in the PR, but downloading the latest develop version of the bootstrap script should help you now. :)

**Comment by forty8bits** [comment]
Looks good @rallytime; the only remaining issue is lack of repositories for 16.10 now. The script currently sets up the broken entry `deb https://repo.saltstack.com/apt/ubuntu/16.10/amd64/latest xenial main`. Installing from git works; it just leaves apt in a broken state.

**Comment by rallytime** [comment]
Yeah the broken entry there is what needs to be cleaned up, which I have done in #1001. That change will add a link to yakkety instead of xenial for 16.10 like so: `deb https://repo.saltstack.com/apt/ubuntu/16.10/amd64/latest yakkety main`. This repo link will 404 for now, but at least we don't have the xenial link in there. If you run the script without a git version, 2016.3.1 will be installed from Ubuntu repos, or you can use the `git` option to get more up-to-date versions, as you noted above.

We can't really do much about the lack of repositories for 16.10 right now from a bootstrap perspective. Our official packaging policy is only to package the LTS releases. However, I discussed this with @dmurphy18 the other day to see how hard a "best effort" support for these kinds of releases will be. I think he is still looking into it. If that is easy to do, the bootstrap script will be ready to go with the change above.

**Comment by rallytime** [comment]
@forty8bits I also have addressed the 16.10 installation version in #1002. That fix addresses the "best effort" approach we take with non-LTS Ubuntu releases: if the non-LTS repo doesn't exist yet from repo.saltstack.com, it will attempt to install the 16.04 packages instead. I have tested this and it works very well. That way 2016.11.1 (or whatever is latest stable or the version you define) will be installed instead from Salt, and the other dependencies will be installed from Ubuntu, without using the git flag.

If a 16.10 repo is added to repo.saltstack.com before the version is EOL-ed, the script can install from there with only a minor fix. Please see [this comment](https://github.com/saltstack/salt-bootstrap/pull/1002#discussion_r93754328) for more information.

**Comment by forty8bits** [comment]
@rallytime coincidentally, I spotted that this morning and tried the bootstrap-salt.sh from your `update-ubuntu-versions` branch; worked perfectly. 👍 I guess we can close this issue once #1002 is merged.

**Comment by rallytime** [comment]
Ah, perfect! Thanks for the update. I'll close this up once the PR is merged. Thanks again for your feedback.

**Comment by rallytime** [comment]
#1002 is merged in. Closing.
