### ISSUE TITLE
salt-bootstrap v2016.10.25 fails to install salt-minion git v2016.3.3 on Ubuntu 16.04

### ISSUE THREAD

**Issue by wes-novack** [saltstack/salt-bootstrap#992]
Description of Issue/Question

salt-cloud 2016.3.4 (using salt-bootstrap v2016.10.25) fails to install salt-minion git v2016.3.3 on Ubuntu 16.04 when using a salt-cloud profile that contains the following line:
script_args: git v2016.3.3

If you use "script_args: git v2016.3.4", it works fine!

salt-cloud error output:

```
INFO: Running install_ubuntu_restart_daemons()
Job for salt-minion.service failed because a configured resource limit was exceeded. See "systemctl status salt-minion.service" and "journalctl -xe" for details.
start: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
ERROR: No init.d support for salt-minion was found
ERROR: Failed to run install_ubuntu_restart_daemons()!!!
Error: There was a profile error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /etc/salt/yourkey.pem -p 22 user@10.1.1.1 'sudo /tmp/.saltcloud-52f41968-3c9a-49ec-93f8-416b96321caf/deploy.sh -c '"'"'/tmp/.saltcloud-52f41968-3c9a-49ec-93f8-416b96321caf'"'"' git v2016.3.3'' failed. Exit code: 1
```

Setup

salt-master and salt-cloud version 2016.3.4 running on CentOS Linux release 7.2.1511 (Core)

Steps to Reproduce Issue

Use a salt-cloud profile named "your-profile" that includes the config line:
script_args: git v2016.3.3

Then attempt to launch an instance
salt-cloud -p your-profile minion-id

Versions Report

```
Salt Version:
Salt: 2016.3.4

Dependency Versions:
cffi: 0.8.6
cherrypy: 3.2.2
dateutil: 1.5
gitdb: 0.6.4
gitpython: 1.0.1
ioflo: Not Installed
Jinja2: 2.7.2
libgit2: 0.21.0
libnacl: Not Installed
M2Crypto: Not Installed
Mako: Not Installed
msgpack-pure: Not Installed
msgpack-python: 0.4.7
mysql-python: Not Installed
pycparser: 2.14
pycrypto: 2.6.1
pygit2: 0.21.4
Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
python-gnupg: 0.3.8
PyYAML: 3.11
PyZMQ: 14.7.0
RAET: Not Installed
smmap: 0.9.0
timelib: Not Installed
Tornado: 4.2.1
ZMQ: 4.0.5

System Versions:
dist: centos 7.2.1511 Core
machine: x86_64
release: 3.10.0-327.22.2.el7.x86_64
system: Linux
version: CentOS Linux 7.2.1511 Core
```

**Comment by heewa** [comment]
I'm seeing this too. Here's the tail end of the debug output from the script from the develop branch:

```
 *  INFO: Running install_ubuntu_git_post()
 * DEBUG: Not overwriting /lib/systemd/system/salt-minion.service with /tmp/git/salt/pkg/deb/salt-minion.service
enabled
 *  INFO: Running install_ubuntu_check_services()
 * DEBUG: Checking if service salt-minion is enabled
 * DEBUG: Service salt-minion is enabled
 *  INFO: Running install_ubuntu_restart_daemons()
 * DEBUG: Waiting 3 seconds for processes to settle before checking for them
 * DEBUG: There's systemd support while checking salt-minion
Job for salt-minion.service failed because a configured resource limit was exceeded. See "systemctl status salt-minion.service" and "journalctl -xe" for details.
 * DEBUG: Failed to start salt-minion using systemd
 * DEBUG: There's upstart support while checking salt-minion
start: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
 * DEBUG: Failed to start salt-minion using Upstart
 * ERROR: No init.d support for salt-minion was found
 * ERROR: Failed to run install_ubuntu_restart_daemons()!!!
 * DEBUG: Cleaning up the Salt Temporary Git Repository
 * DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
```

I don't fully understand the script, nor do I know enough system stuff about Unix or Ubuntu to _really_ diagnose, but from the first two lines of that output you can see that it's going into the first if-block in `install_ubuntu_git_post()` which is taking the `systemd` path, right? But the second branch in that if-block (`elif [ -f /sbin/initctl ]`) is the branch that would write `/etc/default/salt-minion`, which is what `/lib/systemd/system/salt-minion.service` references in the `[Service]` block for `EnvironmentFile` var. But that file doesn't exist after this script runs, and is causing `service salt-minion start` to fail, saying the environment has a problem.


Contents of `/lib/systemd/system/salt-minion.service`:
```
[Unit]
Description=The Salt Minion daemon
After=network.target

[Service]
EnvironmentFile=/etc/default/salt-minion
Type=simple
LimitNOFILE=8192
ExecStart=/usr/bin/salt-minion
KillMode=process
Restart=$RESTART

[Install]
WantedBy=multi-user.target
```

Hope this helps! Also let me know if you want me to try stuff out on an Ubuntu 16.04 box with this or a modified script.

**Comment by rallytime** [comment]
Thanks for reporting this issue @wes-novack and for the helpful debugging information @heewa. We'll have to look into this.

**Comment by vutny** [comment]
I think this is because the `/etc/default/salt-minion` file is not installed during git bootstrap, but it is explicitly required by the `systemd` unit file. Just the error message is misleading though.

In the `2016.3.4` version the `EnvironmentFile` option was dropped.
It could be workarounded by replacing the line with
```
EnvironmentFile-=/etc/default/salt-minion
```
or just creating the file.

As @heewa rightly said, it was broken previously at some point, and the file would be only created for "virtualenv" installation for Ubuntu <= 14.

All this is easy fixable, but the question remains: why SaltStack removed support for reading environment variables from that file? It can be added back with `systemctl edit` of course, but after you would did an upgrade, the file still would remain on the filesystem, and all customizations in it will be silently ignored. Oh bother :wink:

**Comment by rallytime** [comment]
@dmurphy18 Can you provide some of the answers to the questions above? I agree that this should be simple to fix, but it would be good to know if this change was intentional or not from a packaging perspective.

**Comment by dmurphy18** [comment]
@wes-novack @vutny @rallytime This is intentional, we changed how we are handling systemd in 2016.3.4 due to issues with the way we had previously been handling systemd.
see https://github.com/saltstack/salt/commit/fb6e545f78970f8e6dbbee84cccb595ab53702f1 and https://github.com/saltstack/salt/commit/540ec289545cc7a871971d436d6286ee309c2cd2 for the changes.

Also the following issues explain the original problems which resulted in the changes
https://github.com/saltstack/salt/issues/33516
https://github.com/saltstack/salt/pull/35510
https://github.com/saltstack/salt/issues/33803

**Comment by rallytime** [comment]
As this is a known issue with the way the 2016.3.3 release of Salt, but is fixed in later releases, I'm going to close this. We can continue discussion as needed. Thank you all!
